name: Backend CI

on:
  workflow_call:

jobs:
  test-and-lint-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync

      - name: Run Ruff check (Lint)
        run: uv run ruff check .

      - name: Run Ruff format check
        run: uv run ruff format . --check

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: "False"
        run: uv run python manage.py test
