name: Main CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            frontend:
              - "frontend/**"
              - ".github/workflows/frontend_ci.yml"
              - ".github/workflows/main_ci.yml"
            backend:
              - "backend/**"
              - ".github/workflows/backend_ci.yml"
              - ".github/workflows/main_ci.yml"

  frontend-ci:
    needs: changes
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    uses: ./.github/workflows/frontend_ci.yml

  backend-ci:
    needs: changes
    if: ${{ needs.changes.outputs.backend == 'true' }}
    uses: ./.github/workflows/backend_ci.yml

  ci-status-check:
    needs: [frontend-ci, backend-ci]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Check status
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            exit 1
          fi
          echo "All tests and lint passed."
